# Generated by Django 3.2.7 on 2022-02-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0002_auto_20220216_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
